version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:lts

jobs:
  install:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  build:
    parameters:
      node-version: 
        type: string
    docker:
      - image: cimg/node:<< parameters.node-version >>
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: npm run build
  
  lint:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: npm run lint

  test:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: npm run test   

workflows:
  quality-gate:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          matrix:
            parameters:
              node-version: 
                - '10.24'
                - '12.13'
                - '14.19'
                - '16.15'
          requires:
            - install
      - test:
          requires:
            - install
